### PR TITLE
v1.5 tests, incremental merge, temp table fix

### LINKED ISSUE #74: Add support for relevant tests (there's a lot of new ones!)

### PR DESCRIPTION
**Pull request by ilikutle**
#74 Added tests to support v1.5.
Added incremental merge strategy
#85 Fixed not deleting temp_table behaviour when using incremental model

### CODE REVIEW

File: dbt/include/exasol/macros/adapters.sql [hunk 1]
```diff
@@ -21,9 +21,9 @@ ALTER_COLUMN_TYPE_MACRO_NAME = 'alter_column_type'
       lower(table_schema) as [schema],
   	  lower(table_type) as table_type
     from (
-		select table_name,table_schema,'table' as table_type from sys.exa_all_tables
+		select table_name,table_schema,'table' as table_type from sys.exa_user_tables
 		union
-		select view_name, view_schema,'view' from sys.exa_all_views
+		select view_name, view_schema,'view' from sys.exa_user_views
```
Comment (tglunde) [inline dbt/include/exasol/macros/adapters.sql:25]: this had been changed in a previous bugfix. what is the reason to change back to exa_user_views?

**Review by tglunde — COMMENTED** [review]
code changes look ok, except one question regarding dictionary access all vs. user view/table in easol.

File: dbt/include/exasol/macros/adapters.sql (hunk 1 above)
Comment (ilikutle) [reply dbt/include/exasol/macros/adapters.sql]: Switched it back. There was no need to change it.
Exa_user shows only objects owned by user.
Exa_all shows all available to user, so it makes more sense in this case.
